### ISSUE TITLE
A doc about recommend IDE setup for Vaadin 15 with TypeSciprt

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow-and-components-documentation#1138] opened 2020-03-11 08:38 UTC
TypeScript is a highlighted feature in Vaadin 15, but currently, we don't have a recommended IDE set up to help developers get started with it.

DoD:
Having a doc for the recommended setup for different user groups, e.g. 
- For Eclipse users:
- For IntelliJ users:
- For VScode users:
The setup should help the users develop both java code and typescript code efficiently.

**Comment by vlukashov** [comment] 2020-04-28 08:13
duplicate of #1084

**Closed** 2020-04-28 08:13 UTC
Labels: ccdm
